/********************************************************************
* PTFDict.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error PTFDict.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "G__ci.h"
#include "FastAllocString.h"
extern "C" {
extern void G__cpp_setup_tagtablePTFDict();
extern void G__cpp_setup_inheritancePTFDict();
extern void G__cpp_setup_typetablePTFDict();
extern void G__cpp_setup_memvarPTFDict();
extern void G__cpp_setup_globalPTFDict();
extern void G__cpp_setup_memfuncPTFDict();
extern void G__cpp_setup_funcPTFDict();
extern void G__set_cpp_environmentPTFDict();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "Pulse.hh"
#include "ptfEvent.hh"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__PTFDictLN_TClass;
extern G__linked_taginfo G__PTFDictLN_TBuffer;
extern G__linked_taginfo G__PTFDictLN_TMemberInspector;
extern G__linked_taginfo G__PTFDictLN_TObject;
extern G__linked_taginfo G__PTFDictLN_vectorlEunsignedsPshortcOallocatorlEunsignedsPshortgRsPgR;
extern G__linked_taginfo G__PTFDictLN_vectorlEdoublecOallocatorlEdoublegRsPgR;
extern G__linked_taginfo G__PTFDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR;
extern G__linked_taginfo G__PTFDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__PTFDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR;
extern G__linked_taginfo G__PTFDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__PTFDictLN_PTF;
extern G__linked_taginfo G__PTFDictLN_PTFcLcLPulse;
extern G__linked_taginfo G__PTFDictLN_TMatrixTBaselEfloatgR;
extern G__linked_taginfo G__PTFDictLN_TMatrixTBaselEdoublegR;
extern G__linked_taginfo G__PTFDictLN_TVectorTlEfloatgR;
extern G__linked_taginfo G__PTFDictLN_TVectorTlEdoublegR;
extern G__linked_taginfo G__PTFDictLN_TElementActionTlEfloatgR;
extern G__linked_taginfo G__PTFDictLN_TElementPosActionTlEfloatgR;
extern G__linked_taginfo G__PTFDictLN_TMatrixTlEfloatgR;
extern G__linked_taginfo G__PTFDictLN_TMatrixTRow_constlEfloatgR;
extern G__linked_taginfo G__PTFDictLN_TMatrixTRowlEfloatgR;
extern G__linked_taginfo G__PTFDictLN_TMatrixTDiag_constlEfloatgR;
extern G__linked_taginfo G__PTFDictLN_TMatrixTColumn_constlEfloatgR;
extern G__linked_taginfo G__PTFDictLN_TMatrixTFlat_constlEfloatgR;
extern G__linked_taginfo G__PTFDictLN_TMatrixTSub_constlEfloatgR;
extern G__linked_taginfo G__PTFDictLN_TMatrixTSparseRow_constlEfloatgR;
extern G__linked_taginfo G__PTFDictLN_TMatrixTSparseDiag_constlEfloatgR;
extern G__linked_taginfo G__PTFDictLN_TMatrixTColumnlEfloatgR;
extern G__linked_taginfo G__PTFDictLN_TMatrixTDiaglEfloatgR;
extern G__linked_taginfo G__PTFDictLN_TMatrixTFlatlEfloatgR;
extern G__linked_taginfo G__PTFDictLN_TMatrixTSublEfloatgR;
extern G__linked_taginfo G__PTFDictLN_TMatrixTSparseRowlEfloatgR;
extern G__linked_taginfo G__PTFDictLN_TMatrixTSparseDiaglEfloatgR;
extern G__linked_taginfo G__PTFDictLN_TVector3;
extern G__linked_taginfo G__PTFDictLN_PTFcLcLptfEvent;
extern G__linked_taginfo G__PTFDictLN_vectorlEPTFcLcLPulsemUcOallocatorlEPTFcLcLPulsemUgRsPgR;
extern G__linked_taginfo G__PTFDictLN_reverse_iteratorlEvectorlEPTFcLcLPulsemUcOallocatorlEPTFcLcLPulsemUgRsPgRcLcLiteratorgR;

/* STUB derived class for protected member access */
