Roody: MTGListTree Class Reference
MTGListTree Class Reference
#include <MTGListTree.h>
Public Member Functions
MTGListTree (TGWindow *, UInt_t, UInt_t, UInt_t, ULong_t=GetWhitePixel())
MTGListTree (TGCanvas *, UInt_t, ULong_t=GetWhitePixel())
Bool_t HandleButton (Event_t *)
Bool_t HandleKey (Event_t *)
void GetSelectedItems (std::vector< TGListTreeItem * > &)
void GetSelectedItemsRecursive (TGListTreeItem *, std::vector< TGListTreeItem * > &)
Int_t MDeleteItem (TGListTreeItem *)
void MPDeleteChildren (TGListTreeItem *)
Private Types
typedef std::vector
< TGListTreeItem * >::iterator iterator
Private Member Functions
void init ()
Private Attributes
Bool_t fControlPressed
Friends
class TGListTreeItem
Detailed Description
Definition at line 17 of file MTGListTree.h.
Member Typedef Documentation
typedef std::vector<TGListTreeItem*>::iterator MTGListTree::iterator [private]
Definition at line 22 of file MTGListTree.h.
Constructor & Destructor Documentation
MTGListTree::MTGListTree (TGWindow * p, UInt_t w, UInt_t h, UInt_t options, ULong_t back = GetWhitePixel())
Definition at line 42 of file MTGListTree.cxx.
MTGListTree::MTGListTree (TGCanvas * p, UInt_t options, ULong_t back = GetWhitePixel())
Definition at line 47 of file MTGListTree.cxx.
Member Function Documentation
void MTGListTree::GetSelectedItems (std::vector< TGListTreeItem * > & items)
Definition at line 146 of file MTGListTree.cxx.
Referenced by Roody::ProcessMessage().
void MTGListTree::GetSelectedItemsRecursive (TGListTreeItem * item, std::vector< TGListTreeItem * > & items)
Definition at line 153 of file MTGListTree.cxx.
Referenced by GetSelectedItems().
Bool_t MTGListTree::HandleButton (Event_t * event)
Definition at line 91 of file MTGListTree.cxx.
Bool_t MTGListTree::HandleKey (Event_t * event)
Definition at line 164 of file MTGListTree.cxx.
void MTGListTree::init () [private]
Referenced by MTGListTree().
Int_t MTGListTree::MDeleteItem (TGListTreeItem * item)
Definition at line 58 of file MTGListTree.cxx.
Referenced by Roody::CloseSource(), and Roody::DeleteGroup().
void MTGListTree::MPDeleteChildren (TGListTreeItem * item)
Definition at line 71 of file MTGListTree.cxx.
Referenced by MDeleteItem().
Friends And Related Function Documentation
friend class TGListTreeItem [friend]
Definition at line 19 of file MTGListTree.h.
Referenced by GetSelectedItems(), GetSelectedItemsRecursive(), HandleButton(), MDeleteItem(), and MPDeleteChildren().
Member Data Documentation
Bool_t MTGListTree::fControlPressed [private]
Definition at line 23 of file MTGListTree.h.
Referenced by HandleButton(), and HandleKey().
The documentation for this class was generated from the following files:
MTGListTree.h
MTGListTree.cxx