Roody: OptStatMenu Class Reference
OptStatMenu Class Reference
Public Member Functions
OptStatMenu (const TGWindow *w)
Bool_t ProcessMessage (Long_t msg, Long_t parm1, Long_t parm2)
void GetOptStat ()
void SetOptStat ()
Detailed Description
Definition at line 795 of file Roody.cxx.
Constructor & Destructor Documentation
OptStatMenu::OptStatMenu (const TGWindow * w) [inline]
Definition at line 798 of file Roody.cxx.
Member Function Documentation
void OptStatMenu::GetOptStat () [inline]
Definition at line 842 of file Roody.cxx.
Referenced by OptStatMenu().
Bool_t OptStatMenu::ProcessMessage (Long_t msg, Long_t parm1, Long_t parm2) [inline]
Definition at line 822 of file Roody.cxx.
void OptStatMenu::SetOptStat () [inline]
Definition at line 858 of file Roody.cxx.
Referenced by OptStatMenu(), and ProcessMessage().
The documentation for this class was generated from the following file:
Roody.cxx