Roody: Roody Class Reference
Roody Class Reference
#include <Roody.h>
Public Member Functions
Roody (const TGWindow *p=NULL, UInt_t w=800, UInt_t h=800)
virtual ~Roody ()
void RestoreFile (const char *xmlfilename)
bool OpenFile (const char *filename)
void ConnectServer (const char *server, bool complain=true)
void ConnectNetDirectory (const char *server, bool complain=true)
TObject * GetObject (const ObjectPath &src)
TObject * RereadObject (const ObjectPath &src)
Bool_t ProcessMessage (Long_t, Long_t, Long_t)
void CloseWindow ()
void PopupPlot (int, int)
void PopupPlotFolder (int, int)
void PopupPlotSource (int, int)
void PopupTopGroup (int, int)
void PopupGroup (int, int)
TGListTreeItem * PopupNewGroup (int x, int y)
void PeakFind ()
void SelectPad (Int_t, Int_t, Int_t, TObject *)
void AxisLimits ()
void SetCut (TObject *)
void ZoomOption ()
void RefreshAll ()
void RedrawCanvas (TVirtualPad *pad=NULL, bool reread=false)
void AddObjectToVec (PadObjectVec *padvec, TVirtualPad *pad, const ObjectPath *src, TObject *obj, const char *drawOpt)
void AddPadToVec (PadObjectVec *padvec, TVirtualPad *pad, bool reread=false)
ClassDef (Roody, 0)
Protected Types
enum ECommandMenuEntry {
M_NEW_CANVAS, M_REDRAW_CANVAS, M_FILE_OPEN, M_FILE_ONLINE, M_FILE_NetDirectory, M_FILE_SAVE_DEFAULT,
M_FILE_SAVE, M_FILE_RESTORE, M_FILE_EXIT, M_REFRESH_OFF, M_REFRESH_NOW, M_REFRESH_1SEC,
M_REFRESH_3SEC, M_REFRESH_5SEC, M_REFRESH_10SEC, M_REFRESH_DIALOG, M_REOPEN_BUTTON, M_REFRESH_BUTTON,
M_ZONES_11, M_ZONES_12, M_ZONES_13, M_ZONES_21, M_ZONES_22, M_ZONES_33,
M_ZONES_44, M_ZONES_USER, M_ZONES_DIALOG, M_PLOT_NEW, M_PLOT_SAME, M_PLOT_REPLACE,
M_PLOT_NEXT, C_PLOT_FOLDER, C_RESET_FOLDER, C_PLOT_NEW, C_PLOT_SAME, C_PLOT_REPLACE,
C_PLOT_NEXT, C_RESET_OBJECT, C_REOPEN_SOURCE, C_CLOSE_SOURCE, C_NEW_GROUP, C_DELETE_GROUP,
C_DRAW_GROUP, C_ADD_TO_GROUP, C_RESET_GROUP, M_RESET_ALL, M_HELP_ABOUT, M_HELP_CONTENTS,
M_CURRENT_PAD, M_NEXT_PAD, M_NEW_PAD
}
enum EDrawDestination { D_PLOT_DEFAULT = -1, D_PLOT_NEW = M_PLOT_NEW, D_PLOT_SAME = M_PLOT_SAME, D_PLOT_REPLACE = M_PLOT_REPLACE, D_PLOT_NEXT = M_PLOT_NEXT }
typedef std::vector
< TGListTreeItem * > ItemVec
Protected Attributes
MTGListTree * fContents
TGListTreeItem * fTreeItemOnline
TGListTreeItem * fTreeItemFiles
TGListTreeItem * fTreeItemGroups
Private Member Functions
void LayoutGUI ()
void LayoutMenuBar ()
void OpenFileDialog ()
bool OpenRootFile (const char *filename)
bool OpenHbookFile (const char *filename)
bool OpenNetDirectory (const char *dest)
bool OpenXmlServer (const char *url)
void AddDataSource (DataSourceBase *source, MTGListTree *tree, TGListTreeItem *branch, bool reopen=false)
void AddPeakFind ()
void AddAxisLimits ()
void AddSetCut ()
void AddZoomOption ()
void SetupZones (int columns, int rows)
void SetDestination (EDrawDestination newdest)
void PlotItems (const ItemVec *items, EDrawDestination dest)
void UpdateObjectClass (TGListTreeItem *item, TObject *obj)
void DrawItem (TGListTreeItem *item, EDrawDestination dest=D_PLOT_DEFAULT)
void DrawItemOnPad (TGListTreeItem *item, TVirtualPad *dest, bool replace)
void DrawItemsOnNewCanvas (const char *title, const ItemVec *items)
std::string GetZoneSetting (int columns, int rows)
void StartUpdateTimer ()
void SetRefreshRate (int newrefresh)
void OpenRefreshDialog ()
void OpenZoneDialog ()
void UncheckAllZones ()
void CloseSource (TGListTreeItem *item)
void ReopenSource (TGListTreeItem *item)
void GetFolderItems (ItemVec *items, TGListTreeItem *item)
TGListTreeItem * MakeNewGroup (const char *groupname)
void AddToGroup (TGListTreeItem *groupItem, ItemVec *items)
void DeleteGroup (TGListTreeItem *groupItem)
void DrawGroup (TGListTreeItem *groupItem)
void AddHistogramToGroup (TGListTreeItem *groupItem, const char *name, TGListTreeItem *origItem)
void OpenRestoreDialog ()
void OpenSaveDialog ()
void SaveFile (char const *)
void SaveFilePadContents (RoodyXML &xml, std::ofstream &output, std::string space, const PadObjectVec &contents)
std::string GetRunNumber (char const *)
TCanvas * MakeNewCanvas (const char *title, int columns, int rows, int topx=0, int topy=0, int width=0, int height=0)
void SetZonesUser ()
void SetupZonesMenu ()
void ResetAll ()
void ResetMultiple (const ItemVec *items)
void ResetItem (TGListTreeItem *item)
TObject * ApplyCanvasLimits (const CanvasLimits *limits, const ObjectPath *src, TObject *h)
void RestoreObjects (RoodyXML *xml, TVirtualPad *pad, PMXML_NODE parent)
Private Attributes
TGPopupMenu * fMenuRefresh
TGPopupMenu * fMenuZones
TGPopupMenu * fMenuPlot
TGPopupMenu * fPopupMenu
TGStatusBar * fStatusBar
EDrawDestination fDefaultDrawDestination
int fUpdateTimerSec
bool fUpdatePause
int fZoneColumns
int fZoneRows
std::map< TVirtualPad *, int > fCanvasColumns
std::map< TVirtualPad *, int > fCanvasRows
std::vector< std::string > fRootFiles
std::vector< std::string > fHbookFiles
std::vector< std::string > fOnlineFiles
TTimer * fUpdateTimer
ItemVec fGroupFolders
TGPopupMenu * fAddToGroupPopup
int fXSave
int fYSave
Int_t fCanvasCount
std::map< int, CanvasLimits * > fCanvasLimits
TCanvas * fZoomCanvas
TGTextButton * fReopenButton
TGTextButton * fRefreshButton
Static Private Attributes
static TPeakFindPanel * fgPeakFindPanel = 0
Detailed Description
Definition at line 65 of file Roody.h.
Member Typedef Documentation
typedef std::vector<TGListTreeItem*> Roody::ItemVec [protected]
Definition at line 182 of file Roody.h.
Member Enumeration Documentation
enum Roody::ECommandMenuEntry [protected]
Enumerator:
M_NEW_CANVAS
M_REDRAW_CANVAS
M_FILE_OPEN
M_FILE_ONLINE
M_FILE_NetDirectory
M_FILE_SAVE_DEFAULT
M_FILE_SAVE
M_FILE_RESTORE
M_FILE_EXIT
M_REFRESH_OFF
M_REFRESH_NOW
M_REFRESH_1SEC
M_REFRESH_3SEC
M_REFRESH_5SEC
M_REFRESH_10SEC
M_REFRESH_DIALOG
M_REOPEN_BUTTON
M_REFRESH_BUTTON
M_ZONES_11
M_ZONES_12
M_ZONES_13
M_ZONES_21
M_ZONES_22
M_ZONES_33
M_ZONES_44
M_ZONES_USER
M_ZONES_DIALOG
M_PLOT_NEW
M_PLOT_SAME
M_PLOT_REPLACE
M_PLOT_NEXT
C_PLOT_FOLDER
C_RESET_FOLDER
C_PLOT_NEW
C_PLOT_SAME
C_PLOT_REPLACE
C_PLOT_NEXT
C_RESET_OBJECT
C_REOPEN_SOURCE
C_CLOSE_SOURCE
C_NEW_GROUP
C_DELETE_GROUP
C_DRAW_GROUP
C_ADD_TO_GROUP
C_RESET_GROUP
M_RESET_ALL
M_HELP_ABOUT
M_HELP_CONTENTS
M_CURRENT_PAD
M_NEXT_PAD
M_NEW_PAD
Definition at line 106 of file Roody.h.
enum Roody::EDrawDestination [protected]
Enumerator:
D_PLOT_DEFAULT
D_PLOT_NEW
D_PLOT_SAME
D_PLOT_REPLACE
D_PLOT_NEXT
Definition at line 173 of file Roody.h.
Constructor & Destructor Documentation
Roody::Roody (const TGWindow * p = NULL, UInt_t w = 800, UInt_t h = 800)
Definition at line 208 of file Roody.cxx.
Roody::~Roody () [virtual]
Definition at line 741 of file Roody.cxx.
Member Function Documentation
void Roody::AddAxisLimits () [private]
Definition at line 972 of file Roody.cxx.
Referenced by Roody().
void Roody::AddDataSource (DataSourceBase * source, MTGListTree * tree, TGListTreeItem * branch, bool reopen = false) [private]
Definition at line 2385 of file Roody.cxx.
Referenced by ConnectServer(), OpenNetDirectory(), OpenRootFile(), OpenXmlServer(), and ReopenSource().
void Roody::AddHistogramToGroup (TGListTreeItem * groupItem, const char * name, TGListTreeItem * origItem) [private]
Definition at line 2241 of file Roody.cxx.
Referenced by AddToGroup(), and RestoreFile().
void Roody::AddObjectToVec (PadObjectVec * padvec, TVirtualPad * pad, const ObjectPath * src, TObject * obj, const char * drawOpt)
Definition at line 1107 of file Roody.cxx.
Referenced by AddPadToVec(), DrawItemOnPad(), and ZoomOption().
void Roody::AddPadToVec (PadObjectVec * padvec, TVirtualPad * pad, bool reread = false)
Definition at line 1181 of file Roody.cxx.
Referenced by RedrawCanvas(), and SetupZones().
void Roody::AddPeakFind () [private]
Definition at line 1332 of file Roody.cxx.
Referenced by Roody().
void Roody::AddSetCut () [private]
Definition at line 948 of file Roody.cxx.
Referenced by Roody().
void Roody::AddToGroup (TGListTreeItem * groupItem, ItemVec * items) [private]
Definition at line 1649 of file Roody.cxx.
Referenced by ProcessMessage().
void Roody::AddZoomOption () [private]
Definition at line 1276 of file Roody.cxx.
Referenced by Roody().
TObject * Roody::ApplyCanvasLimits (const CanvasLimits * limits, const ObjectPath * src, TObject * h) [private]
Definition at line 996 of file Roody.cxx.
Referenced by AddObjectToVec().
void Roody::AxisLimits ()
Definition at line 985 of file Roody.cxx.
Roody::ClassDef (Roody , 0)
void Roody::CloseSource (TGListTreeItem * item) [private]
Definition at line 2270 of file Roody.cxx.
Referenced by ProcessMessage().
void Roody::CloseWindow ()
Definition at line 2346 of file Roody.cxx.
Referenced by ProcessMessage().
void Roody::ConnectNetDirectory (const char * server, bool complain = true)
Definition at line 2748 of file Roody.cxx.
Referenced by ProcessMessage().
void Roody::ConnectServer (const char * server, bool complain = true)
Definition at line 2768 of file Roody.cxx.
Referenced by ProcessMessage(), and RestoreFile().
void Roody::DeleteGroup (TGListTreeItem * groupItem) [private]
Definition at line 1659 of file Roody.cxx.
Referenced by ProcessMessage().
void Roody::DrawGroup (TGListTreeItem * groupItem) [private]
Definition at line 1740 of file Roody.cxx.
Referenced by ProcessMessage().
void Roody::DrawItem (TGListTreeItem * item, EDrawDestination dest = D_PLOT_DEFAULT) [private]
Definition at line 1435 of file Roody.cxx.
Referenced by PlotItems().
void Roody::DrawItemOnPad (TGListTreeItem * item, TVirtualPad * dest, bool replace) [private]
Definition at line 1457 of file Roody.cxx.
Referenced by DrawItem(), DrawItemsOnNewCanvas(), and RestoreObjects().
void Roody::DrawItemsOnNewCanvas (const char * title, const ItemVec * items) [private]
Definition at line 1720 of file Roody.cxx.
Referenced by DrawGroup(), and ProcessMessage().
void Roody::GetFolderItems (ItemVec * items, TGListTreeItem * item) [private]
Definition at line 2290 of file Roody.cxx.
Referenced by DrawGroup(), ProcessMessage(), and SaveFile().
TObject * Roody::GetObject (const ObjectPath & src)
Definition at line 126 of file Roody.cxx.
Referenced by AddPadToVec(), ApplyCanvasLimits(), DrawItemOnPad(), RereadObject(), SaveFilePadContents(), and ZoomOption().
std::string Roody::GetRunNumber (char const * filename) [private]
Definition at line 2610 of file Roody.cxx.
std::string Roody::GetZoneSetting (int columns, int rows) [private]
Definition at line 1354 of file Roody.cxx.
Referenced by SaveFile().
void Roody::LayoutGUI () [private]
Definition at line 753 of file Roody.cxx.
Referenced by Roody().
void Roody::LayoutMenuBar () [private]
Definition at line 871 of file Roody.cxx.
Referenced by LayoutGUI().
TCanvas * Roody::MakeNewCanvas (const char * title, int columns, int rows, int topx = 0, int topy = 0, int width = 0, int height = 0) [private]
Definition at line 1673 of file Roody.cxx.
Referenced by DrawItem(), DrawItemsOnNewCanvas(), ProcessMessage(), RestoreFile(), and SetupZones().
TGListTreeItem * Roody::MakeNewGroup (const char * groupname) [private]
Definition at line 1634 of file Roody.cxx.
Referenced by PopupNewGroup(), and RestoreFile().
bool Roody::OpenFile (const char * filename)
Definition at line 2354 of file Roody.cxx.
Referenced by OpenFileDialog(), and RestoreFile().
void Roody::OpenFileDialog () [private]
Definition at line 2366 of file Roody.cxx.
Referenced by ProcessMessage().
bool Roody::OpenHbookFile (const char * filename) [private]
Referenced by OpenFile().
bool Roody::OpenNetDirectory (const char * dest) [private]
Definition at line 2498 of file Roody.cxx.
Referenced by ConnectNetDirectory().
void Roody::OpenRefreshDialog () [private]
Definition at line 2876 of file Roody.cxx.
Referenced by ProcessMessage().
void Roody::OpenRestoreDialog () [private]
Definition at line 2946 of file Roody.cxx.
Referenced by ProcessMessage().
bool Roody::OpenRootFile (const char * filename) [private]
Definition at line 2438 of file Roody.cxx.
Referenced by OpenFile().
void Roody::OpenSaveDialog () [private]
Definition at line 2926 of file Roody.cxx.
Referenced by ProcessMessage().
bool Roody::OpenXmlServer (const char * url) [private]
Definition at line 2477 of file Roody.cxx.
Referenced by ConnectServer().
void Roody::OpenZoneDialog () [private]
Definition at line 2887 of file Roody.cxx.
Referenced by ProcessMessage().
void Roody::PeakFind ()
Definition at line 1535 of file Roody.cxx.
void Roody::PlotItems (const ItemVec * items, EDrawDestination dest) [private]
Definition at line 2339 of file Roody.cxx.
Referenced by ProcessMessage().
void Roody::PopupGroup (int x, int y)
Definition at line 1609 of file Roody.cxx.
Referenced by ProcessMessage().
TGListTreeItem * Roody::PopupNewGroup (int x, int y)
Definition at line 1620 of file Roody.cxx.
Referenced by AddToGroup(), and ProcessMessage().
void Roody::PopupPlot (int x, int y)
Definition at line 1543 of file Roody.cxx.
Referenced by ProcessMessage().
void Roody::PopupPlotFolder (int x, int y)
Definition at line 1569 of file Roody.cxx.
Referenced by ProcessMessage().
void Roody::PopupPlotSource (int x, int y)
Definition at line 1583 of file Roody.cxx.
Referenced by ProcessMessage().
void Roody::PopupTopGroup (int x, int y)
Definition at line 1600 of file Roody.cxx.
Referenced by ProcessMessage().
Bool_t Roody::ProcessMessage (Long_t msg, Long_t parm1, Long_t parm2)
Definition at line 1821 of file Roody.cxx.
void Roody::RedrawCanvas (TVirtualPad * pad = NULL, bool reread = false)
Definition at line 1229 of file Roody.cxx.
Referenced by ProcessMessage(), and RefreshAll().
void Roody::RefreshAll ()
Definition at line 2857 of file Roody.cxx.
Referenced by ProcessMessage(), and ResetAll().
void Roody::ReopenSource (TGListTreeItem * item) [private]
Definition at line 2251 of file Roody.cxx.
Referenced by ProcessMessage().
TObject * Roody::RereadObject (const ObjectPath & src)
Definition at line 176 of file Roody.cxx.
Referenced by AddPadToVec().
void Roody::ResetAll () [private]
Definition at line 2303 of file Roody.cxx.
Referenced by ProcessMessage().
void Roody::ResetItem (TGListTreeItem * item) [private]
Definition at line 2328 of file Roody.cxx.
Referenced by ResetMultiple().
void Roody::ResetMultiple (const ItemVec * items) [private]
Definition at line 2322 of file Roody.cxx.
Referenced by ProcessMessage().
void Roody::RestoreFile (const char * xmlfilename)
Definition at line 389 of file Roody.cxx.
Referenced by OpenRestoreDialog().
void Roody::RestoreObjects (RoodyXML * xml, TVirtualPad * pad, PMXML_NODE parent) [private]
Definition at line 354 of file Roody.cxx.
Referenced by RestoreFile().
void Roody::SaveFile (char const * xmlFilename) [private]
Definition at line 633 of file Roody.cxx.
Referenced by OpenSaveDialog(), and ProcessMessage().
void Roody::SaveFilePadContents (RoodyXML & xml, std::ofstream & output, std::string space, const PadObjectVec & contents) [private]
Definition at line 609 of file Roody.cxx.
Referenced by SaveFile().
void Roody::SelectPad (Int_t ev, Int_t x, Int_t y, TObject * obj)
Definition at line 1428 of file Roody.cxx.
void Roody::SetCut (TObject * o)
Definition at line 957 of file Roody.cxx.
void Roody::SetDestination (EDrawDestination newdest) [private]
Definition at line 1345 of file Roody.cxx.
Referenced by LayoutMenuBar(), MakeNewCanvas(), ProcessMessage(), and SetupZones().
void Roody::SetRefreshRate (int newrefresh) [private]
Definition at line 1759 of file Roody.cxx.
Referenced by OpenRefreshDialog(), ProcessMessage(), and RestoreFile().
void Roody::SetupZones (int columns, int rows) [private]
Definition at line 1361 of file Roody.cxx.
Referenced by OpenZoneDialog(), and ProcessMessage().
void Roody::SetupZonesMenu () [private]
Definition at line 532 of file Roody.cxx.
Referenced by OpenZoneDialog(), ProcessMessage(), and RestoreFile().
void Roody::SetZonesUser () [private]
Definition at line 599 of file Roody.cxx.
Referenced by SetupZonesMenu().
void Roody::StartUpdateTimer () [private]
Definition at line 2842 of file Roody.cxx.
Referenced by RefreshAll(), Roody(), and SetRefreshRate().
void Roody::UncheckAllZones () [private]
Definition at line 1809 of file Roody.cxx.
Referenced by ProcessMessage(), and SetupZonesMenu().
void Roody::UpdateObjectClass (TGListTreeItem * item, TObject * obj) [private]
Definition at line 2627 of file Roody.cxx.
Referenced by DrawItemOnPad().
void Roody::ZoomOption ()
Definition at line 1289 of file Roody.cxx.
Member Data Documentation
TGPopupMenu* Roody::fAddToGroupPopup [private]
Definition at line 217 of file Roody.h.
Referenced by Roody().
std::map<TVirtualPad*,int> Roody::fCanvasColumns [private]
Definition at line 206 of file Roody.h.
Referenced by MakeNewCanvas(), RedrawCanvas(), SaveFile(), and SetupZones().
Int_t Roody::fCanvasCount [private]
Definition at line 220 of file Roody.h.
Referenced by MakeNewCanvas(), and Roody().
std::map<int,CanvasLimits*> Roody::fCanvasLimits [private]
Definition at line 222 of file Roody.h.
Referenced by AddObjectToVec(), and AxisLimits().
std::map<TVirtualPad*,int> Roody::fCanvasRows [private]
Definition at line 207 of file Roody.h.
Referenced by MakeNewCanvas(), RedrawCanvas(), SaveFile(), and SetupZones().
MTGListTree* Roody::fContents [protected]
Definition at line 184 of file Roody.h.
Referenced by AddHistogramToGroup(), CloseSource(), ConnectServer(), DeleteGroup(), LayoutGUI(), MakeNewGroup(), OpenNetDirectory(), OpenRootFile(), OpenXmlServer(), ProcessMessage(), ReopenSource(), RestoreFile(), and UpdateObjectClass().
EDrawDestination Roody::fDefaultDrawDestination [private]
Definition at line 198 of file Roody.h.
Referenced by DrawItem(), and SetDestination().
TPeakFindPanel * Roody::fgPeakFindPanel = 0 [static, private]
Definition at line 196 of file Roody.h.
Referenced by PeakFind().
ItemVec Roody::fGroupFolders [private]
Definition at line 215 of file Roody.h.
Referenced by DeleteGroup(), MakeNewGroup(), PopupPlot(), ProcessMessage(), and SaveFile().
std::vector<std::string> Roody::fHbookFiles [private]
Definition at line 210 of file Roody.h.
TGPopupMenu* Roody::fMenuPlot [private]
Definition at line 192 of file Roody.h.
Referenced by LayoutMenuBar(), and SetDestination().
TGPopupMenu* Roody::fMenuRefresh [private]
Definition at line 190 of file Roody.h.
Referenced by LayoutMenuBar(), and SetRefreshRate().
TGPopupMenu* Roody::fMenuZones [private]
Definition at line 191 of file Roody.h.
Referenced by LayoutMenuBar(), ProcessMessage(), SetupZonesMenu(), SetZonesUser(), and UncheckAllZones().
std::vector<std::string> Roody::fOnlineFiles [private]
Definition at line 211 of file Roody.h.
Referenced by ConnectServer(), OpenXmlServer(), ResetAll(), and SaveFile().
TGPopupMenu* Roody::fPopupMenu [private]
Definition at line 193 of file Roody.h.
Referenced by PopupGroup(), PopupPlot(), PopupPlotFolder(), PopupPlotSource(), PopupTopGroup(), and Roody().
TGTextButton* Roody::fRefreshButton [private]
Definition at line 227 of file Roody.h.
Referenced by LayoutGUI(), and SetRefreshRate().
TGTextButton* Roody::fReopenButton [private]
Definition at line 226 of file Roody.h.
Referenced by LayoutGUI().
std::vector<std::string> Roody::fRootFiles [private]
Definition at line 209 of file Roody.h.
Referenced by OpenNetDirectory(), and ResetAll().
TGStatusBar* Roody::fStatusBar [private]
Definition at line 194 of file Roody.h.
Referenced by CloseSource(), ConnectServer(), GetObject(), LayoutGUI(), OpenFileDialog(), OpenRefreshDialog(), OpenRestoreDialog(), OpenSaveDialog(), OpenZoneDialog(), ProcessMessage(), ReopenSource(), RestoreFile(), Roody(), and SaveFile().
TGListTreeItem* Roody::fTreeItemFiles [protected]
Definition at line 186 of file Roody.h.
Referenced by LayoutGUI(), OpenRootFile(), RestoreFile(), and SaveFile().
TGListTreeItem* Roody::fTreeItemGroups [protected]
Definition at line 187 of file Roody.h.
Referenced by LayoutGUI(), MakeNewGroup(), ProcessMessage(), and RestoreFile().
TGListTreeItem* Roody::fTreeItemOnline [protected]
Definition at line 185 of file Roody.h.
Referenced by ConnectServer(), LayoutGUI(), OpenNetDirectory(), and OpenXmlServer().
bool Roody::fUpdatePause [private]
Definition at line 201 of file Roody.h.
Referenced by ProcessMessage(), Roody(), SetRefreshRate(), and StartUpdateTimer().
TTimer* Roody::fUpdateTimer [private]
Definition at line 213 of file Roody.h.
Referenced by CloseWindow(), RefreshAll(), Roody(), StartUpdateTimer(), and ~Roody().
int Roody::fUpdateTimerSec [private]
Definition at line 200 of file Roody.h.
Referenced by ProcessMessage(), Roody(), SaveFile(), SetRefreshRate(), and StartUpdateTimer().
int Roody::fXSave [private]
Definition at line 218 of file Roody.h.
Referenced by PopupPlot(), PopupPlotFolder(), and PopupPlotSource().
int Roody::fYSave [private]
Definition at line 218 of file Roody.h.
Referenced by PopupPlot(), PopupPlotFolder(), and PopupPlotSource().
int Roody::fZoneColumns [private]
Definition at line 203 of file Roody.h.
Referenced by DrawItem(), ProcessMessage(), RestoreFile(), Roody(), SaveFile(), SetupZones(), SetupZonesMenu(), and SetZonesUser().
int Roody::fZoneRows [private]
Definition at line 204 of file Roody.h.
Referenced by DrawItem(), ProcessMessage(), RestoreFile(), Roody(), SaveFile(), SetupZones(), SetupZonesMenu(), and SetZonesUser().
TCanvas* Roody::fZoomCanvas [private]
Definition at line 224 of file Roody.h.
Referenced by Roody(), and ZoomOption().
The documentation for this class was generated from the following files:
Roody.h
Roody.cxx