Roody: RoodyXML Class Reference
RoodyXML Class Reference
#include <RoodyXML.h>
Public Member Functions
int FindNode (PMXML_NODE parent, int startIndex, const char *name)
PMXML_NODE GetNode (PMXML_NODE parent, int index)
std::string GetNodeString (PMXML_NODE node, int index)
RoodyXML ()
virtual ~RoodyXML ()
std::ofstream & OpenFileForWrite (char const *)
std::string Encode (std::string const &)
bool OpenFileForRead (char const *)
Public Attributes
unsigned int level_
bool elementIsOpen_
std::vector< std::string > names_
std::ofstream outputFile_
char const * encoding_
char const * version_
PMXML_NODE documentNode_
PMXML_NODE roodyNode_
PMXML_NODE histParent_
Detailed Description
Definition at line 21 of file RoodyXML.h.
Constructor & Destructor Documentation
RoodyXML::RoodyXML ()
Definition at line 14 of file RoodyXML.cxx.
RoodyXML::~RoodyXML () [virtual]
Definition at line 20 of file RoodyXML.cxx.
Member Function Documentation
std::string RoodyXML::Encode (std::string const & src)
Definition at line 59 of file RoodyXML.cxx.
Referenced by Roody::SaveFile(), and Roody::SaveFilePadContents().
int RoodyXML::FindNode (PMXML_NODE parent, int startIndex, const char * name)
Definition at line 109 of file RoodyXML.cxx.
Referenced by OpenFileForRead(), Roody::RestoreFile(), and Roody::RestoreObjects().
PMXML_NODE RoodyXML::GetNode (PMXML_NODE parent, int index)
Definition at line 119 of file RoodyXML.cxx.
Referenced by Roody::RestoreFile(), and Roody::RestoreObjects().
std::string RoodyXML::GetNodeString (PMXML_NODE node, int index)
Definition at line 127 of file RoodyXML.cxx.
Referenced by Roody::RestoreFile(), and Roody::RestoreObjects().
bool RoodyXML::OpenFileForRead (char const * file)
Definition at line 89 of file RoodyXML.cxx.
Referenced by Roody::RestoreFile().
std::ofstream & RoodyXML::OpenFileForWrite (char const * file)
Definition at line 23 of file RoodyXML.cxx.
Referenced by Roody::SaveFile().
Member Data Documentation
PMXML_NODE RoodyXML::documentNode_
Definition at line 30 of file RoodyXML.h.
Referenced by OpenFileForRead().
bool RoodyXML::elementIsOpen_
Definition at line 25 of file RoodyXML.h.
char const* RoodyXML::encoding_
Definition at line 28 of file RoodyXML.h.
Referenced by OpenFileForWrite(), and RoodyXML().
PMXML_NODE RoodyXML::histParent_
Definition at line 30 of file RoodyXML.h.
unsigned int RoodyXML::level_
Definition at line 24 of file RoodyXML.h.
std::vector<std::string> RoodyXML::names_
Definition at line 26 of file RoodyXML.h.
std::ofstream RoodyXML::outputFile_
Definition at line 27 of file RoodyXML.h.
Referenced by OpenFileForWrite().
PMXML_NODE RoodyXML::roodyNode_
Definition at line 30 of file RoodyXML.h.
Referenced by OpenFileForRead(), and Roody::RestoreFile().
char const* RoodyXML::version_
Definition at line 29 of file RoodyXML.h.
Referenced by OpenFileForWrite(), and RoodyXML().
The documentation for this class was generated from the following files:
RoodyXML.h
RoodyXML.cxx