Roody: Roody.cxx File Reference
Roody.cxx File Reference
#include <stdio.h>
#include <math.h>
#include "RoodyXML.h"
#include "Roody.h"
#include "TAxisLimitsDialog.h"
#include "TROOT.h"
#include "TCutG.h"
#include "TNtuple.h"
#include "TGraph.h"
#include "TVirtualX.h"
#include "TGListTree.h"
#include "TGClient.h"
#include "TGLabel.h"
#include "TGButton.h"
#include "TGMsgBox.h"
#include "TGMenu.h"
#include "TGCanvas.h"
#include "TGTextDialog.h"
#include "TCanvas.h"
#include "TFrame.h"
#include "TH1.h"
#include "TSystem.h"
#include "TFile.h"
#include "TKey.h"
#include "TGStatusBar.h"
#include "TExec.h"
#include "TStyle.h"
#include "TTimer.h"
#include "TContextMenu.h"
#include "TClassMenuItem.h"
#include "TSocket.h"
#include "MTGListTree.h"
#include "TPeakFindPanel.h"
#include "TGFileDialog.h"
#include "TPaveLabel.h"
#include "DataSourceBase.h"
#include "DataSourceTDirectory.h"
#include "DataSourceTNetFolder.h"
#include "DataSourceTFile.h"
#include "DataSourceXmlServer.h"
Classes
class MemDebug
class OptStatMenu
Typedefs
typedef std::map< std::string,
DataSourceBase * > DataSourcesMap
Enumerations
enum Action { A_ITEM = 1, A_FOLDER = 2, A_SOURCE = 3, A_GROUP = 4 }
Functions
void breakhere (void)
static TGListTreeItem * FindItem (ObjectPath src)
ClassImp (Roody)
static std::string PathToString (const ObjectPath &src)
static std::vector< std::string > split (char sep, const std::string &str)
static std::vector< int > toInt (const std::vector< std::string > &vec)
static ObjectPath StringToPath (const std::string &source)
static void DrawVec (TVirtualPad *canvas, const PadObjectVec *padvec)
static void CopyAttrs (TObject *dest, TObject *src)
Variables
TList * gAllObjects = NULL
std::map< TGListTreeItem
*, Action > gItemActions
std::map< ObjectPath, TObject * > gObjectCache
DataSourcesMap gDataSources
std::map< TGListTreeItem
*, ObjectPath > gItemSources
std::map< ObjectPath, std::string > gObjectClasses
std::map< std::string,
std::vector< TGListTreeItem * > > gGroupContents
std::map< TVirtualPad
*, PadObjectVec > gPadContents
Typedef Documentation
typedef std::map<std::string,DataSourceBase*> DataSourcesMap
Definition at line 104 of file Roody.cxx.
Enumeration Type Documentation
enum Action
Enumerator:
A_ITEM
A_FOLDER
A_SOURCE
A_GROUP
Definition at line 90 of file Roody.cxx.
Function Documentation
void breakhere (void)
Definition at line 53 of file Roody.cxx.
Referenced by MemDebug::~MemDebug().
ClassImp (Roody)
static void CopyAttrs (TObject * dest, TObject * src) [static]
Definition at line 1143 of file Roody.cxx.
Referenced by Roody::AddPadToVec().
static void DrawVec (TVirtualPad * canvas, const PadObjectVec * padvec) [static]
Definition at line 1070 of file Roody.cxx.
Referenced by Roody::DrawItemOnPad(), Roody::RedrawCanvas(), Roody::SetupZones(), and Roody::ZoomOption().
static TGListTreeItem* FindItem (ObjectPath src) [static]
Definition at line 112 of file Roody.cxx.
Referenced by MTGListTree::HandleButton(), Roody::RestoreFile(), and Roody::RestoreObjects().
static std::string PathToString (const ObjectPath & src) [static]
Definition at line 262 of file Roody.cxx.
Referenced by Roody::SaveFile(), and Roody::SaveFilePadContents().
static std::vector<std::string> split (char sep, const std::string & str) [static]
Definition at line 273 of file Roody.cxx.
Referenced by Roody::ConnectServer(), Roody::OpenZoneDialog(), Roody::RestoreFile(), and StringToPath().
static ObjectPath StringToPath (const std::string & source) [static]
Definition at line 312 of file Roody.cxx.
Referenced by Roody::RestoreFile(), and Roody::RestoreObjects().
static std::vector<int> toInt (const std::vector< std::string > & vec) [static]
Definition at line 304 of file Roody.cxx.
Referenced by Roody::OpenZoneDialog(), and Roody::RestoreFile().
Variable Documentation
TList* gAllObjects = NULL
Definition at line 98 of file Roody.cxx.
Referenced by Roody::AddObjectToVec(), Roody::AddPadToVec(), and Roody::Roody().
DataSourcesMap gDataSources
Definition at line 105 of file Roody.cxx.
Referenced by Roody::AddDataSource(), Roody::CloseSource(), Roody::GetObject(), Roody::ProcessMessage(), Roody::ReopenSource(), Roody::ResetAll(), and Roody::ResetItem().
std::map<std::string,std::vector<TGListTreeItem*> > gGroupContents
Definition at line 110 of file Roody.cxx.
std::map<TGListTreeItem*, Action> gItemActions
Definition at line 100 of file Roody.cxx.
Referenced by Roody::AddDataSource(), Roody::AddHistogramToGroup(), Roody::GetFolderItems(), Roody::MakeNewGroup(), and Roody::ProcessMessage().
std::map<TGListTreeItem*,ObjectPath> gItemSources
Definition at line 107 of file Roody.cxx.
Referenced by Roody::AddDataSource(), Roody::AddHistogramToGroup(), Roody::DrawItemOnPad(), FindItem(), Roody::ResetItem(), and Roody::SaveFile().
std::map<ObjectPath,TObject*> gObjectCache
Definition at line 102 of file Roody.cxx.
Referenced by Roody::GetObject(), Roody::ProcessMessage(), Roody::ReopenSource(), and Roody::RereadObject().
std::map<ObjectPath,std::string> gObjectClasses
Definition at line 108 of file Roody.cxx.
Referenced by Roody::DrawItemOnPad().
std::map<TVirtualPad*,PadObjectVec> gPadContents
Definition at line 202 of file Roody.cxx.
Referenced by Roody::AddPadToVec(), Roody::DrawItemOnPad(), DrawVec(), Roody::RedrawCanvas(), Roody::SaveFile(), Roody::SetupZones(), and Roody::ZoomOption().